### ISSUE TITLE
Error whet start

### ISSUE THREAD

**Issue by SerhiiZahuba** [hnimminh/sip-healthcheck#1]
If run programm

python3 siphealthcheck.py  or python siphealthcheck.py  i have an error

Traceback (most recent call last):
  File "siphealthcheck.py", line 48, in <module>
    raise Exception(error)
Exception: 'module' object has no attribute 'config'

**Comment by hnimminh** [comment]
this repo developed to run with python2, (python2 is deprecated some lib has been removed). decide to archive this project and write the new one with compiled one.
